### ISSUE TITLE
Run mounting host application?? 

### ISSUE THREAD

**Issue by sodacrackers** [wadmiraal/docker-drupal#10]
The project looks great and thank you for posting code.  I'm trying it for a Docker introduction and to run Drush on an existing site.  

Is it possible pointing the image to existing host files and a mysql instance? My site is running on the host laptop IIS (but no drush).  I'm seeing a "no site found" error when trying the project: 

```
alpin@nick-hp MINGW64 /c/www/docker
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              c11854b254d2        About an hour ago   714.9 MB
docker-whale        latest              20fbd3f19fef        39 hours ago        274.2 MB
debian              wheezy              5e2a9df259d2        12 days ago         84.89 MB
....
wadmiraal/drupal    7.41                e72766b0c738        6 weeks ago         631.2 MB

alpin@nick-hp MINGW64 /c/www/docker
$ docker run -v $(pwd):/c/www/wyc.intranet.uw.edu/washyacht/ drush/drush cc all -y
No Drupal site found, only 'drush' cache was cleared.                  [warning]





```

**Comment by wrender** [comment]
I don't think this would work, because the docker includes a mysql instance, database and the drupal files already inside of the container.  One thing you could do is use a docker that just includes a LAMP. (Linux, Apache, MYSQL & PHP) and then mount your Drupal directory inside of it, and import your database into it using PHPMyAdmin.

**Comment by wadmiraal** [comment]
Well, I think it _could_ work. It's just not that straightforward :-). And it will require either an already installed Drupal, or that you re-install it by hand.

**First, the files**

You can mount the Drupal code _over_ the code in the image. Just use something like this:

```
docker run -v /my/local/drupal/code/:/var/www ... wadmiraal/drupal
```

This will override the code in the image at `/var/www` (where the Drupal code is located) with the code on your local machine at `/my/local/drupal/code/` (or, `cd` inside `/my/local/drupal/code/` and use `-v $(pwd):/var/www`, like in your example). This will of course overwrite the `settings.php` file; hence, you will not "use" the Drupal that was installed inside the image.

**Second, MySQL**

Where is your MySQL? Inside another Docker container? Or somewhere else?

_If inside another container:_

You can tell Docker to _link_ containers together. Before, this was done using the `--link` option, like so:

```
docker run --link mysql_container_id:mysqlhost ... wadmiraal/drupal
```

This will make the MySQL container available as `mysqlhost` inside the `wadmiraal/drupal` container. So, in your Drupal `settings.php` file, you would put the MySQL hostname/IP as `mysqlhost` (instead of `localhost`, for example).

But now, this has been deprecated in favour of [Docker networks](https://docs.docker.com/engine/userguide/networking/dockernetworks/). I have never used them, so you will need to read the documentation.

_If somewhere else:_

If MySQL is running on the host server/computer, you can use the IP Docker assigns to your machine. This is usually `172.17.42.1`, but can vary ([1st answer with a quick Google search](http://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container)).

If MySQL is available at any IP in your network, just use that IP. Docker has access to your network through the host.
