### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by ckr123** [wadmiraal/docker-drupal#17]
Cannot get HTTPS to work
Everytime i redirect to a https site on my test site i get "SSL_ERROR_RX_RECORD_TOO_LONG"

**Comment by wadmiraal** [comment]
I see you closed this issue :-). In fact, I found it quite interesting, because the container was missing SSL support out of the box. As of now, the latest `8` and `7` builds support SSL, and expose the 443 port. Meaning you can now run a container like so:

```
docker run -d -p 8443:443 -p 8022:22 -t wadmiraal/drupal
```

And access the site at `https://localhost:8443`. This is not retro-active, though. All older tags (like `7.44` or `8.1.2`) don't support HTTPS.

**Comment by ckr123** [comment]
Hi yeah found the solution myself, so closed the case,  i've should have posted the answer. But thank you for the reply. :)
