### ISSUE TITLE
Docker is not building anymore because of missing default.settings.php

### ISSUE THREAD

**Issue by j3ll3nl** [wadmiraal/docker-drupal#18]
They changed the default.settings.php files to example.*

This would fix the building of the latest Drupal 8 modules

**Comment by wadmiraal** [comment]
Aha, that's why! I was wondering why the latest builds failed, but didn't have the time yesterday to investigate. Thanks, will fix ASAP.

**Comment by j3ll3nl** [comment]
Now that i am checking it it doesn't seem to be the issue. I overlooked it. We should continue our search :p

**Comment by wadmiraal** [comment]
It looked as if the latest build of Drupal Console was faulty (happens often, actually...). I will look at it again.

**Comment by wrender** [comment]
Wouldn't it be more reliable to use Drush?

**Comment by j3ll3nl** [comment]
I would use Composer to install it globally.

```
composer global require drupal/console:~1.0 \
--prefer-dist \
--optimize-autoloader \
--sort-packages
```

Copied and altered from https://github.com/hechoendrupal/DrupalConsole/#download-using-drupalcomposer

**Comment by wrender** [comment]
Composer also seems like a good option too. It looks like drupal console is commercially supported so it is too bad it is often broken for this type of thing as it looks like a great option.

**Comment by wadmiraal** [comment]
During my first attempts with Drupal Console, I did use Composer to install it globally. But at the time there wasn't a stable release, so it kept failing. Using the installer (http://drupalconsole.com/installer) did work, so I've left it as-is ever since. But you are right, now that stable releases are out, I will move to that approach. At least I can pinpoint it to a certain release, and make sure that builds don't fail randomly anymore.

**Comment by wadmiraal** [comment]
It worked. Thanks for your help and input.
