### ISSUE TITLE
Documentation: How to make mysql database persistant?

### ISSUE THREAD

**Issue by pminf** [wadmiraal/docker-drupal#21]
After stopping and restarting the container all database changes seem to be gone. So how do I make the database persistant? Could you please document it in your readme.

**Comment by wadmiraal** [comment]
It does persist. If you only stop and start, it will persist your data. However, if you *remove* it, then yes, it will also remove your data. In my examples, I usually put `--rm`, and no `-d`. This means the process stays in the foreground, and once stopped (via `^C`), it will remove the container (and all its data). This is the way I usually use it: it frees me from having to clean up old containers (which can quickly take up *a lot* of space), and I can quickly spin up new, clean environments.

But, if you want to keep your data, simply do not put the `--rm` flag in there. When stopping the container, it will keep your database state.

However, let me explain the way I use it when I need to keep some form of database state. Say, for a particular project, I need some database state to remain (some module installations and config). Instead of keeping a container, and continuing to work on it, I commit the state to its own image. This way, I can quickly re-create new environments from a given starting point. This is much more flexible than keeping a single container, and if I mess up my installation, I can just come back to the previous state.

You can commit a docker container state like so:

    # First, get the container ID. Or, if you gave it a name, you can use the name instead.
    $ docker ps
    # Then, commit the state to its own image. You can even tag them, if needed.
    $ docker commit [container-id] [image-name]
    # For example:
    $ docker commit 678420fa94e9 wadmiraal/project-name

Then, the next time I want to use that state as a starting point, I just use `wadmiraal/project-name` instead of `wadmiraal/drupal`. And if I decide to install and configure another module, and want to this new state to be my starting point, I just re-commit, overwriting the previous image. Simple.

Hope this helps.
