### ISSUE TITLE
403 forbidden issues & apache

### ISSUE THREAD

**Issue by ajlee** [wadmiraal/docker-drupal#23]
I've been following the tutorial at wadmiraal.net/lore/2015/03/27/use-docker-to-kickstart-your-drupal-development/ and have been having problems with folder permssions and apache.

I've put up a post on serverfault about it - see https://serverfault.com/questions/864902/403-forbidden-on-apache-2-4-10

I'm a bit a of a n00b with docker so forgive me if I'm missing something obvious!

**Comment by wadmiraal** [comment]
Oh wow, so sorry for the extremely late reply.

Did you figure it out since? If not, it was probably related to the fact that the webroot now contained a folder "drupal", and didn't know what to do with it. You would now need to go to http://localhost:PORT/drupal/web/; simply going to http://localhost:PORT wouldn't work.
