### ISSUE TITLE
module install error on docker build

### ISSUE THREAD

**Issue by wrender** [wadmiraal/docker-drupal#5]
Looks like maybe an issue with the drupal console. I'm not familiar with it...

 [InvalidArgumentException]  
  Command "module:install" is not defined.  
  Did you mean one of these?  
      site:install  
      module:download                       

The command '/bin/sh -c /etc/init.d/mysql start &&  cd /var/www &&  drupal module:download admin_toolbar 8.x-1.10 &&    drupal module:install admin_toolbar &&  drupal module:install simpletest' returned a non-zero code: 1

**Comment by wadmiraal** [comment]
Probably a bug in the latest Drupal Console. It is the correct command:
https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/module-install.html

**Comment by wrender** [comment]
Ok. Thanks @wadmiraal .  Will try again later.

**Comment by wrender** [comment]
Tried again now. Still not working.

**Comment by wadmiraal** [comment]
Blasted... The Dockerfile is simply using the latest installer found on
the drupalconsole.com website (http://drupalconsole.com/installer). But the
site:install command seems to work, right?

If you wish, you can comment out the following lines (near the end of the
Dockerfile):

RUN /etc/init.d/mysql start && \
    cd /var/www && \
    drupal module:download admin_toolbar 8.x-1.10 && \
    drupal module:install admin_toolbar && \
    drupal module:install simpletest

It's not critical. It just installs 2 handy modules, but you don't need
them.

Let's hope they fix this soon. They are releasing new versions pretty
often: https://github.com/hechoendrupal/DrupalConsole/releases  Maybe it's
already solved, just not deployed on the website yet.

**Comment by wrender** [comment]
This problem seems to only be effecting the 8.x/master branch.  I can bring up the 7.x branch no problem.

On a side note; If I wanted to work on drupal files themselves locally, for example the /index.php file, and use xdebug locally with sublime text 3, on a Ubuntu 14.04 OS how would I go about mounting the data containers?

**Comment by wadmiraal** [comment]
Yes. The 7.x branch uses Drush, which works fine. The master branch (which
is for Drupal 8) uses Drupal Console, which is the culprit.

If you wanted to manipulate Drupal itself, you have to download a local
copy of Drupal, and launch the container, mounting `/var/www/` to the
location of your local Drupal code. This would also mean you will have to
go through the install procedure manually (because `settings.php` will be
overridden). The reason is, mounting only works one way: you can mount your
files to the container, but you cannot mount the container's files to you.

For using Xdebug locally with Sublime... I don't know. As the whole shebang
lives inside a container, I don't know how Sublime could access it. If it's
possible via SSH, that's probably the best option.

**Comment by wrender** [comment]
Thanks @wadmiraal .  I sent you two pull requests.  Let me know what you think.

**Comment by wadmiraal** [comment]
Updated to latest Drupal Console, updated calls. It builds fine (for now).
